# Generated by Django 5.0.7 on 2024-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
