# Generated by Django 5.0.7 on 2024-07-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_auto_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='answer_to',
            new_name='replied_comment',
        ),
    ]
