services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    working_dir: /code

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: starnavi_test
      POSTGRES_USER: starnavi_test
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: .
    command: celery -A starnavi_test worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbitmq
    working_dir: /code

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: starnavi_test
      RABBITMQ_DEFAULT_PASS: 1234

volumes:
  postgres_data:
